export enum ActionTypes {
  CHECK_AUTH = 'CHECK_AUTH',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  LOAD_USER_DATA = 'LOAD_USER_DATA',
  REQUEST_FRIEND = 'REQUEST_FRIEND',
  ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST',
  REJECT_FRIEND_REQUEST = 'REJECT_FRIEND_REQUEST',
  LIST_FRIENDS = 'LIST_FRIENDS',
  UPDATE_FRIEND_RELATIONSHIP = 'UPDATE_FRIEND_RELATIONSHIP',
  UNFRIEND = 'UNFRIEND',
  BLOCK_FRIEND = 'BLOCK_FRIEND',
  GET_STATUSES = 'GET_STATUSES'
}
